version: '3.8'

services:
  pushoo-chan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pushoo-chan-gover
    image: pushoo-chan-gover:latest
    ports:
      - "8084:8084"
    # 移除data目录挂载（核心修改）
    volumes:
       - /home/docker/pushoogolang:/app/data
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    network_mode: "bridge"
    # （可选）若仍报权限错，临时用root运行
    user: "root:root"